"""add date and priorit fields to todo table

Revision ID: 07f5c00d1485
Revises: 
Create Date: 2026-02-09 19:51:44.563366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f5c00d1485'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('todos', sa.Column('priority', sa.String(length=20), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_column('todos', 'priority')
    op.drop_column('todos', 'due_date')
    # ### end Alembic commands ###
