"""Add password column

Revision ID: cdb752de693f
Revises: 08f5c00d1485
Create Date: 2026-06-18 15:19:06.775955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb752de693f'
down_revision = '08f5c00d1485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # 1. Add the column as nullable first
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))

    # 2. Backfill existing rows with a placeholder value
    op.execute("UPDATE users SET password_hash = 'unset' WHERE password_hash IS NULL")

    # 3. Now enforce NOT NULL
    op.alter_column('users', 'password_hash', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.alter_column('todos', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
